In [3]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
np.random.seed(0)

In [76]:
a = np.random.randint(10,size = 6)
b = np.random.randint(10, size = (5,6))
c = np.random.randint(10, size = (4,5,6))
d = np.random.randint(10, size = (4,5,6,7))

In [21]:
d.shape

(4, 5, 6, 7)

In [23]:
d.ndim

4

In [24]:
d.size

840

In [25]:
d.dtype

dtype('int64')

In [26]:
d.itemsize

8

In [27]:
d.nbytes

6720

In [29]:
b

array([[3, 5, 7, 2, 7, 1],
       [6, 5, 0, 0, 3, 1],
       [9, 9, 6, 6, 7, 8],
       [8, 7, 0, 8, 6, 8],
       [9, 8, 3, 6, 1, 7]])

In [33]:
b[1:4,1:5] = 99
b

array([[ 7,  2,  3,  9,  5,  4],
       [ 0, 99, 99, 99, 99,  4],
       [ 8, 99, 99, 99, 99,  9],
       [ 4, 99, 99, 99, 99,  7],
       [ 0,  8,  1,  2,  8,  5]])

In [43]:
x = np.arange(25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
x[20:0:-5]

array([20, 15, 10,  5])

In [61]:
b

array([[3, 7, 4, 2, 0, 9],
       [2, 2, 9, 6, 8, 9],
       [1, 1, 1, 0, 1, 7],
       [0, 6, 5, 9, 8, 5],
       [6, 8, 1, 4, 5, 9]])

In [62]:
b[::-1,::-1]

array([[9, 5, 4, 1, 8, 6],
       [5, 8, 9, 5, 6, 0],
       [7, 1, 0, 1, 1, 1],
       [9, 8, 6, 9, 2, 2],
       [9, 0, 2, 4, 7, 3]])

In [68]:
b[:,4]

array([0, 8, 1, 8, 5])

In [70]:
c = b[:,:]

In [71]:
c

array([[3, 7, 4, 2, 0, 9],
       [2, 2, 9, 6, 8, 9],
       [1, 1, 1, 0, 1, 7],
       [0, 6, 5, 9, 8, 5],
       [6, 8, 1, 4, 5, 9]])

In [72]:
c[0] =0

In [73]:
c

array([[0, 0, 0, 0, 0, 0],
       [2, 2, 9, 6, 8, 9],
       [1, 1, 1, 0, 1, 7],
       [0, 6, 5, 9, 8, 5],
       [6, 8, 1, 4, 5, 9]])

In [74]:
b

array([[0, 0, 0, 0, 0, 0],
       [2, 2, 9, 6, 8, 9],
       [1, 1, 1, 0, 1, 7],
       [0, 6, 5, 9, 8, 5],
       [6, 8, 1, 4, 5, 9]])

In [77]:
b

array([[0, 2, 7, 6, 6, 7],
       [7, 0, 9, 4, 1, 4],
       [9, 5, 9, 0, 6, 4],
       [4, 1, 7, 0, 1, 2],
       [8, 7, 9, 8, 0, 0]])

In [80]:
c = b.copy()

In [82]:
c[::2,:] =0

In [83]:
c

array([[0, 0, 0, 0, 0, 0],
       [7, 0, 9, 4, 1, 4],
       [0, 0, 0, 0, 0, 0],
       [4, 1, 7, 0, 1, 2],
       [0, 0, 0, 0, 0, 0]])

In [89]:
grid = np.arange(36)
grid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [90]:
grid.reshape((4,3,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [91]:
grid

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [92]:
grid.reshape((3,3,2,2))

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35]]]])

In [93]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
x.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [101]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
x.shape

(10,)

In [106]:
x = x[np.newaxis,:]

In [107]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [108]:
x.shape

(1, 10)

In [110]:
x[np.newaxis,:].shape

(1, 1, 10)

In [111]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [113]:
y = np.arange(4)
y

array([0, 1, 2, 3])

In [118]:
y[np.newaxis,:]

array([[0, 1, 2, 3]])

In [121]:
y[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3]])

In [125]:
x1 = np.array([1,2,3])
x2 = np.array([4,5,6])
x3 = np.array([9,7,5])

In [128]:
np.concatenate([x1,x2,x3])

array([1, 2, 3, 4, 5, 6, 9, 7, 5])

In [129]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [132]:
np.concatenate([grid, grid], axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [133]:
np.vstack([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [135]:
np.hstack([grid, grid])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [149]:
a = np.array([1,2,3,4,5])[np.newaxis,:]
b = np.arange(6,21).reshape((3,5))
c = np.arange(16,31).reshape((3,5))

In [153]:
np.concatenate([b,c], axis = 1)

array([[ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15, 21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20, 26, 27, 28, 29, 30]])

In [159]:
x = np.arange(1,51)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [166]:
x1, x2, x3, x4 = np.split(x, [5,15,35])

In [169]:
x3

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35])

In [170]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [173]:
upper, lower = np.vsplit(grid, [2])
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [174]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [175]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [176]:
left, right = np.hsplit(grid, [2])
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [177]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])