In [68]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
np.random.seed(42)

In [10]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
np.array([1,2,3,4.6])

array([1. , 2. , 3. , 4.6])

In [13]:
np.array([1,2,3,4.6,'7'])

array(['1', '2', '3', '4.6', '7'], dtype='<U32')

In [21]:
np.array([1,2,3,4,5], dtype= 'int32')

array([1, 2, 3, 4, 5], dtype=int32)

In [65]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [67]:
np.linspace(10, 20,8)

array([10.        , 11.42857143, 12.85714286, 14.28571429, 15.71428571,
       17.14285714, 18.57142857, 20.        ])

In [70]:
np.random.random((4,5))

array([[0.73199394, 0.59865848, 0.15601864, 0.15599452, 0.05808361],
       [0.86617615, 0.60111501, 0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224],
       [0.52475643, 0.43194502, 0.29122914, 0.61185289, 0.13949386]])

In [71]:
np.random.random((3,3))

array([[0.29214465, 0.36636184, 0.45606998],
       [0.78517596, 0.19967378, 0.51423444],
       [0.59241457, 0.04645041, 0.60754485]])

In [72]:
np.random.normal(0,1,(3,3))

array([[-0.60025385,  0.94743982,  0.291034  ],
       [-0.63555974, -1.02155219, -0.16175539],
       [-0.5336488 , -0.00552786, -0.22945045]])

In [73]:
np.random.uniform(0,5,(3,4))

array([[3.31261142, 1.55855538, 2.60034011, 2.7335514 ],
       [0.92427228, 4.84792314, 3.87566412, 4.69749471],
       [4.47413675, 2.98949989, 4.60937118, 0.44246251]])

In [74]:
np.random.uniform(0,10,(4,5))

array([[1.95982862, 0.45227289, 3.25330331, 3.8867729 , 2.71349032],
       [8.28737509, 3.56753327, 2.8093451 , 5.42696083, 1.40924225],
       [8.02196981, 0.74550644, 9.86886937, 7.72244769, 1.98715682],
       [0.05522117, 8.15461428, 7.06857344, 7.29007168, 7.71270347]])

In [75]:
np.random.normal(0,10,(4,5))

array([[  3.89348913,  -2.0716589 ,  -6.23477395, -15.0815329 ,
         10.99646976],
       [ -1.77732121,  -4.10383309,  11.79716345,  -8.98207939,
          8.34795419],
       [  2.96561384, -10.37829877,  -0.75803745,   9.72963534,
          7.95595464],
       [ 14.95434253,   3.38181252,  33.72296254,  -9.20390805,
         -3.9863839 ]])

In [76]:
np.random.randint(0,10,(3,4))

array([[2, 6, 0, 3],
       [3, 4, 6, 6],
       [3, 6, 2, 5]])

In [77]:
np.random.choice(np.arange(100), 9)

array([27, 65, 41, 44, 61, 56,  5, 27, 27])

In [78]:
np.random.rand(4,5)

array([[2.18440437e-01, 4.16509948e-01, 8.83280259e-01, 3.24345021e-01,
        1.22087955e-01],
       [3.56297838e-01, 9.06828442e-01, 2.72132249e-01, 6.47690121e-01,
        5.20376995e-04],
       [3.52568856e-01, 3.04781258e-01, 1.64655853e-01, 5.34089419e-01,
        4.84829971e-01],
       [6.92436033e-01, 2.69412334e-01, 2.44125522e-01, 1.68291042e-01,
        2.18764220e-01]])

In [79]:
np.random.sample(3)

array([0.558102  , 0.40383617, 0.06489225])

In [80]:
np.random.normal?