In [74]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

from pandas import Series, DataFrame
from scipy import special

sns.set()

In [7]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1/values[i]
    return output

In [8]:
values = np.random.randint(1,10,5)
compute_reciprocals(values)

array([0.16666667, 0.11111111, 0.2       , 0.5       , 0.14285714])

In [11]:
big_array = np.random.randint(1,1000, size = 10000000)
%timeit compute_reciprocals(big_array)

2.65 s ± 22.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [13]:
np.add(x, 5)

array([5, 6, 7, 8, 9])

In [14]:
np.subtract(x,5)

array([-5, -4, -3, -2, -1])

In [15]:
np.multiply(x, 5)

array([ 0,  5, 10, 15, 20])

In [16]:
np.divide(x,5)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [20]:
np.negative(x)

array([ 0, -1, -2, -3, -4])

In [27]:
np.power(x,2)

array([ 0,  1,  4,  9, 16])

In [28]:
np.power(x,5)

array([   0,    1,   32,  243, 1024])

In [31]:
np.power(np.negative(np.add(np.multiply(x,2),2)),2)

array([  4,  16,  36,  64, 100])

In [33]:
np.add(x,2)

array([2, 3, 4, 5, 6])

In [34]:
x

array([0, 1, 2, 3, 4])

In [36]:
y = np.arange(5,10)
y

array([5, 6, 7, 8, 9])

In [37]:
np.add(x,y)

array([ 5,  7,  9, 11, 13])

In [38]:
np.subtract(x,y)

array([-5, -5, -5, -5, -5])

In [39]:
np.negative(x)

array([ 0, -1, -2, -3, -4])

In [42]:
np.divide(y,2)

array([2.5, 3. , 3.5, 4. , 4.5])

In [43]:
np.floor_divide(y,2)

array([2, 3, 3, 4, 4])

In [44]:
np.mod(x,2)

array([0, 1, 0, 1, 0])

In [45]:
np.mod(y,3)

array([2, 0, 1, 2, 0])

In [46]:
np.floor_divide(y,2)

array([2, 3, 3, 4, 4])

In [47]:
theta = np.linspace(0, np.pi,3)
theta

array([0.        , 1.57079633, 3.14159265])

In [48]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [49]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [50]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [51]:
np.arcsin(theta)

/var/folders/b3/2_by4h4x5vj2swvvx86hmbw00000gn/T/ipykernel_11255/458218287.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(theta)


array([ 0., nan, nan])

In [53]:
x = [-1,0,1]
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [54]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [55]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

In [56]:
x = [1,2,3]
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [57]:
np.exp2(x)

array([2., 4., 8.])

In [58]:
np.power(3,x)

array([ 3,  9, 27])

In [59]:
np.exp2(x)

array([2., 4., 8.])

In [60]:
np.power(2,x)

array([2, 4, 8])

In [61]:
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [64]:
x = np.arange(1,10)

In [65]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [66]:
np.log2(x)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [67]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [68]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [69]:
np.exp2(x)

array([  2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [70]:
np.expm1(x)

array([1.71828183e+00, 6.38905610e+00, 1.90855369e+01, 5.35981500e+01,
       1.47413159e+02, 4.02428793e+02, 1.09563316e+03, 2.97995799e+03,
       8.10208393e+03])

In [71]:
np.expm1x(x)

array([1.71828183e+00, 6.38905610e+00, 1.90855369e+01, 5.35981500e+01,
       1.47413159e+02, 4.02428793e+02, 1.09563316e+03, 2.97995799e+03,
       8.10208393e+03])

In [72]:
np.expm1(x)

array([1.71828183e+00, 6.38905610e+00, 1.90855369e+01, 5.35981500e+01,
       1.47413159e+02, 4.02428793e+02, 1.09563316e+03, 2.97995799e+03,
       8.10208393e+03])

In [73]:
np.log1p(x)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [75]:
x = [1,3,6,8,12]
x

[1, 3, 6, 8, 12]

In [76]:
special.gamma(x)

array([1.00000e+00, 2.00000e+00, 1.20000e+02, 5.04000e+03, 3.99168e+07])

In [77]:
special.gammaln(x)

array([ 0.        ,  0.69314718,  4.78749174,  8.52516136, 17.50230785])

In [78]:
special.beta(x,2)

array([0.5       , 0.08333333, 0.02380952, 0.01388889, 0.00641026])

In [79]:
x = np.array([0,0.3,0.6,0.8,1])
x

array([0. , 0.3, 0.6, 0.8, 1. ])

In [80]:
special.erf(x)

array([0.        , 0.32862676, 0.60385609, 0.74210096, 0.84270079])

In [81]:
special.erfc(x)

array([1.        , 0.67137324, 0.39614391, 0.25789904, 0.15729921])

In [82]:
special.erfinv(x)

array([0.        , 0.27246271, 0.59511608, 0.9061938 ,        inf])

In [87]:
x = np.arange(1,11)
y = np.empty(10)
np.multiply(x, 10, out = y)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [88]:
y

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [91]:
z

array([2.000e+00, 0.000e+00, 4.000e+00, 1.000e+00, 8.000e+00, 0.000e+00,
       1.600e+01, 1.000e+00, 3.200e+01, 1.000e+00, 6.400e+01, 1.000e+00,
       1.280e+02, 0.000e+00, 2.560e+02, 1.000e+00, 5.120e+02, 0.000e+00,
       1.024e+03, 1.000e+00])

In [89]:
z = np.empty(20)
np.exp2(x, out = z[::2])

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [90]:
z

array([2.000e+00, 0.000e+00, 4.000e+00, 1.000e+00, 8.000e+00, 0.000e+00,
       1.600e+01, 1.000e+00, 3.200e+01, 1.000e+00, 6.400e+01, 1.000e+00,
       1.280e+02, 0.000e+00, 2.560e+02, 1.000e+00, 5.120e+02, 0.000e+00,
       1.024e+03, 1.000e+00])

In [92]:
x = np.arange(1,51)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [98]:
np.add.reduce(x)

1275

In [105]:
x = np.arange(1,16)
np.multiply.reduce(x)

1307674368000

In [107]:
np.add.accumulate(x)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120])

In [108]:
np.multiply.accumulate(x)

array([            1,             2,             6,            24,
                 120,           720,          5040,         40320,
              362880,       3628800,      39916800,     479001600,
          6227020800,   87178291200, 1307674368000])

In [109]:
np.sum(x)

120

In [111]:
np.product(x)

1307674368000

In [112]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])