In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('ggplot')

In [3]:
np.random.seed(0)

In [4]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] =  1.0 / values[i]
    return output

In [6]:
values = np.random.randint(1, 10, size = 5)
%timeit compute_reciprocals(values)

8.05 µs ± 200 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [7]:
big_array = np.random.randint(1, 100, size = 100000)
%timeit compute_reciprocals(big_array)

148 ms ± 2.45 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [9]:
x+5

array([5, 6, 7, 8])

In [10]:
x-5

array([-5, -4, -3, -2])

In [11]:
x*2

array([0, 2, 4, 6])

In [13]:
x/2

array([0. , 0.5, 1. , 1.5])

In [14]:
x//2

array([0, 0, 1, 1])

In [15]:
-x

array([ 0, -1, -2, -3])

In [16]:
x**2

array([0, 1, 4, 9])

In [17]:
x %2

array([0, 1, 0, 1])

In [19]:
(0.5 * x +1)**2

array([1.  , 2.25, 4.  , 6.25])

In [21]:
np.add(x,2)

array([2, 3, 4, 5])

In [22]:
np.subtract(x, 2)

array([-2, -1,  0,  1])

In [23]:
np.negative(x)

array([ 0, -1, -2, -3])

In [24]:
np.multiply(x, 2)

array([0, 2, 4, 6])

In [25]:
np.divide(x, 3)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [26]:
np.floor_divide(x,3)

array([0, 0, 0, 1])

In [27]:
np.power(x,2)

array([0, 1, 4, 9])

In [28]:
np.mod(x,3)

array([0, 1, 2, 0])

In [29]:
x = np.array([1,2,3,-4,-5,6,-7])
x

array([ 1,  2,  3, -4, -5,  6, -7])

In [30]:
np.abs(x)

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
np.absolute(x)

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [35]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [36]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [37]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [38]:
np.arcsin(theta)

/var/folders/b3/2_by4h4x5vj2swvvx86hmbw00000gn/T/ipykernel_14016/458218287.py:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(theta)


array([ 0., nan, nan])

In [39]:
x = [-1,0,1]
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [40]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [41]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

In [42]:
x = [1, 2, 3]
x

[1, 2, 3]

In [43]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [44]:
np.exp2(x)

array([2., 4., 8.])

In [45]:
np.power(3, x)

array([ 3,  9, 27])

In [46]:
x = [1,2,3,4,5,6,7,8,9,10]
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [47]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [48]:
np.log2(x)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809])

In [49]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [50]:
np.exp2(x)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [51]:
np.power(3, x)

array([    3,     9,    27,    81,   243,   729,  2187,  6561, 19683,
       59049])

In [52]:
np.expm1(x)

array([1.71828183e+00, 6.38905610e+00, 1.90855369e+01, 5.35981500e+01,
       1.47413159e+02, 4.02428793e+02, 1.09563316e+03, 2.97995799e+03,
       8.10208393e+03, 2.20254658e+04])

In [53]:
np.log1p(x)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527])

In [54]:
from scipy import special

In [55]:
x = [1,2,3,4,5]

In [56]:
special.gamma(x)

array([ 1.,  1.,  2.,  6., 24.])

In [57]:
special.gammaln(x)

array([0.        , 0.        , 0.69314718, 1.79175947, 3.17805383])

In [58]:
special.beta(x, 2)

array([0.5       , 0.16666667, 0.08333333, 0.05      , 0.03333333])

In [59]:
special.erf(x)

array([0.84270079, 0.99532227, 0.99997791, 0.99999998, 1.        ])

In [60]:
special.erfc(x)

array([1.57299207e-01, 4.67773498e-03, 2.20904970e-05, 1.54172579e-08,
       1.53745979e-12])

In [61]:
special.erfcinv(x)

array([ -0., -inf,  nan,  nan,  nan])

In [63]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out = y)
y

array([ 0., 10., 20., 30., 40.])

In [64]:
y

array([ 0., 10., 20., 30., 40.])

In [65]:
y = np.zeros(10)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
np.power(2,x, out = y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [67]:
x

array([0, 1, 2, 3, 4])

In [68]:
np.power(2,x)

array([ 1,  2,  4,  8, 16])

In [69]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [70]:
np.add.reduce(x)

15